### PR TITLE
Jdk6

### PR DESCRIPTION
**Pull request by hrotkogabor**
Please create a jdk6 compatible version too.
Thanx

Note: I had to comment out the sign plugin in pom.xml.

### CODE REVIEW

**Comment by monitorjbl** [comment]
I appreciate that you may need to use Java 6  @hrotkogabor, but I don't want to support it directly. It's been end of life for years now, and I really don't want to break Java 7 syntax compatibility for others. 

I hope you understand, and you're more than welcome to fork the code and create your own Java 6 compatible version.

**Comment by hrotkogabor** [comment]
Thanx, I made my jdk6 fork, linking your original project.
https://github.com/hrotkogabor/xlsx-streamer-jdk6

2015-05-26 14:21 GMT+02:00 Taylor Jones <notifications@github.com>:

**Comment by jeancl** [comment]
hrotkogabor I already made same thing a two months ago.
If you want, can use my version for Java 6 only including it on your pom. 

https://github.com/jeancl/excel-streaming-reader

<dependency>
    <groupId>br.com.beardsoft</groupId>
    <artifactId>jxlsx-streamer</artifactId>
    <version>0.0.1</version>
</dependency>

**Comment by jeancl** [comment]
hrotkogabor I already made same thing a two months ago.
If you want, can use my version for Java 6 only including it on your pom. 

https://github.com/jeancl/excel-streaming-reader

**Comment by hrotkogabor** [comment]
Thank you, it works great!

**Pull request closed without merging**
