### PR TITLE
Update Xerces to 2.11.0

### PR DESCRIPTION
**Pull request by slugmandrew**
This one should be good

### CODE REVIEW

**Comment by slugmandrew** [comment]
Hmm, what am I doing wrong? I created a fresh fork and project and changed one line! :(

**Comment by slugmandrew** [comment]
Possibly the new version is causing some issue?

**Comment by monitorjbl** [comment]
I think Shippable had some weird issue, I retriggered the build and it went through. Let me take a quick look at this with Maven before I merge this to make sure it's not going to have conflicts with anything else.

**Comment by monitorjbl** [comment]
Yep, looks good; no competing dependencies on xerces in this library. Thanks for the PR!

**Comment by slugmandrew** [comment]
Absolute pleasure. It's a fine tool :+1:

**Pull request merged**
