### PR TITLE
Fix NullPointerException on empty sheet

### PR DESCRIPTION
**Pull request by matthiasblaesing**
When testing this project for use @work I had an immediate crash. I tracked it down to the event/row handling that failed if an empty sheet was parsed.

I moved the row handling into the event handler and made getRow just return the info whether the new iterator had a "nextElement".

The existing unittests still work and a new test was added to cover this case.

[Review on Reviewable](https://reviewable.io/reviews/monitorjbl/excel-streaming-reader/9)

### CODE REVIEW

**Comment by monitorjbl** [comment]
I'll need to take a closer look at this, but +1 already for the unit test!

**Comment by monitorjbl** [comment]
Looks pretty good! Thanks for restructuring that code a bit, it looks a lot cleaner now. Just get hose two little issues resolved and I can merge it and release it out to Maven Central.

**Comment by matthiasblaesing** [comment]
I agree with your points - I pushed the fixes.

**Comment by monitorjbl** [comment]
Thanks for the submission! I'll get this released tonight.

**Pull request merged**
