### PR TITLE
#181 update currentColNum when column contains an explicit offset

### LINKED ISSUE #181: Next cols mapped incorrectly when column contains an offset
When column starts with an offset next columns are not taking the offset into the account.
For example this column would cause a problem:
```
<['http://schemas.openxmlformats.org/spreadsheetml/2006/main']::c r='Y2421' t='s'>
```
The most likely cause is that variable `currentColNum` isn't updated with the offset.

### PR DESCRIPTION
**Pull request by PanAeon**
fixes #181

### CODE REVIEW

**Comment by PanAeon** [comment]
@monitorjbl, the file on which I get this error is relatively large (622Kb) and contains confidential info, so I can't provide it. When i try to edit the file on mac os, and then save it the error goes away. Maybe different versions of the office save files differently, but at the moment I'm not  sure how to reproduce  this in the unit test.

**Comment by monitorjbl** [comment]
Could you perhaps edit the raw XML of a small workbook to reproduce the conditions of the larger one? Without an example to test in the build, your fix will likely regress in the future.

**Comment by PanAeon** [comment]
Hi, yeah, I tried to do that before, but got invalid file, probably because I zipped it wrongly. 
I have added a test case, and verified that it is actually failing without the fix.

**Comment by PanAeon** [comment]
@monitorjbl I've added the necessary changes. 
We've got some problems on production because of this issue. As we can't use streaming mode in `spark-excel` and without streaming mode a 60Mb file can apparently bring down our entire spark cluster (15Gb of memory on executor).

**Comment by monitorjbl** [comment]
Looks good to me :+1:

**Pull request merged**
