### PR TITLE
fixed formula reference issues

### PR DESCRIPTION
**Pull request by apixandru**
This pull request fixes two issues
1. Formulas that operated on numbers were being converted to string.

> In StreamingWorkbookTest#testFormulaCells we had cells A1 with value 1 and A2 with value 2, cell A3 which was sum of A1 and A2 had value "3" instead of 3

2. Formulas that included dates were losing the date format
  > For instance in StreamingWorkbookTest#testNumericFormattedFormulaCell we had cells C1 with value May 11 2018 and C2 with value C1 was returning "43231" which is the numeric value of C1, unformatted and also converted to a string

In my opinion, since this is likely to cause a regression on people expecting the old behavior, It would probably be a good idea to increment the major version or at least the minor one.

### CODE REVIEW

**Comment by apixandru** [comment]
anyone alive in here? :)

**Comment by monitorjbl** [comment]
Sorry, started a new job and I haven't had much time to review these PRs. I agree that this will need a version bump. I'm going to hold off merging this until I can get the other changes released.

**Comment by apixandru** [comment]
No worries, I just wanted to make sure that someone had a chance to look over this. I have rebased the change on top of the new code changes to solve the conflicts.

**Comment by siddharth96** [comment]
Any update on when this change can be merged?

**Pull request merged**
