### PR TITLE
See description in https://github.com/monitorjbl/excel-streaming-read…

### PR DESCRIPTION
**Pull request by alusbars**
Please look at description in https://github.com/monitorjbl/excel-streaming-reader/issues/100

### CODE REVIEW

**Comment by shawnsmith** [comment]
I ran into this bug as well.  IMHO #105 has a better way of fixing the problem.

**Comment by monitorjbl** [comment]
#105 is merged now, and I think it does in fact address this particular issue. Can you confirm @alusbars ?

**Comment by monitorjbl** [comment]
I'm going to go ahead and close this, but if you think it should be reopened just let me know!

**Comment by alusbars** [comment]
@monitorjbl confirm. Thanks!

**Pull request closed without merging**
